project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    comments:
      hypothesis: true
    code-fold: true
  pdf:
    link-citations: true
    pdf-engine: xelatex
    documentclass: article
    geometry: margin=2.5cm
    toc: true
    number-sections: true
    colorlinks: true
    keep-tex: true

execute:
  freeze: true
